name: flutter_app
description: Another v2ex unoffical app in flutter.And 'V2lf' means 'way to love flutter'.

version: 2019.6+20

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ^0.5.3+5
  url_launcher: ^5.2.5
  cached_network_image: ^1.1.1 # https://pub.dartlang.org/packages/cached_network_image
  html: ^0.14.0+3 # https://pub.flutter-io.cn/packages/html
  xpath: ^0.1.0 # https://pub.flutter-io.cn/packages/xpath     还不支持 ETree.toString(Element) :(
  dio: ^2.1.7 # https://pub.dartlang.org/packages/dio
  # flutter_html_view: ^0.5.10 # https://pub.flutter-io.cn/packages/flutter_html_view "Thus, flutter_html_view ^0.5.10 requires url_launcher ^3.0.0."
  flutter_html: ^0.11.0 # https://github.com/Sub6Resources/flutter_html
  fluttertoast: ^3.1.3 # https://pub.dartlang.org/packages/fluttertoast
  # flutter_inappbrowser: ^0.5.51 #https://pub.dartlang.org/packages/flutter_inappbrowser
  # flame: ^0.10.2
  path_provider: ^1.1.0 # https://pub.dartlang.org/packages/path_provider#-installing-tab-
  sqflite: ^1.1.6+1 # https://pub.dev/packages/sqflite#-installing-tab-
  # modal_progress_hud: ^0.1.3 # https://github.com/mmcc007/modal_progress_hud
  ovprogresshud: ^0.2.5 # https://github.com/mjl0602/OVProgressHUD
  # event_bus: ^1.0.3 # https://pub.dartlang.org/packages/event_bus
  # flare_flutter: ^1.5.1 # https://pub.dartlang.org/packages/flare_flutter#-installing-tab-
  flare_flutter:
    git:
      url: https://github.com/2d-inc/Flare-Flutter.git
      path: flare_flutter
      ref: dev
  share: ^0.6.2+1 # https://pub.dartlang.org/packages/share#-installing-tab-
  launch_review: ^2.0.0 # https://pub.dartlang.org/packages/launch_review#-installing-tab-
  font_awesome_flutter: ^8.4.0 # https://pub.dartlang.org/packages/font_awesome_flutter#-installing-tab-
  webfeed: ^0.4.2 # https://github.com/witochandra/webfeed
  flutter_whatsnew: ^1.0.0 # https://pub.dartlang.org/packages/flutter_whatsnew#-installing-tab-
  shimmer: ^1.0.1
  zefyr: ^0.8.0 # https://pub.dartlang.org/packages/zefyr#-installing-tab-
  #    zefyr:
  #      git:
  #        url: https://github.com/memspace/zefyr.git
  #        ref: dev
  #        path: packages/zefyr
  photo_view: ^0.4.2
  # webview_flutter: ^0.3.6 无法弹出键盘输入的问题还没解决
  flutter_webview_plugin: ^0.3.8
  flutter_local_notifications: ^0.7.1+3 # https://pub.dev/packages/flutter_local_notifications#-installing-tab-
  provider: ^3.1.0 # https://pub.dev/packages/provider
  device_info: ^0.4.0+3
  liquid_pull_to_refresh: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/images/icon/ic_launcher.png
  image_path_ios: assets/images/icon/ios.png
  adaptive_icon_background: "#607D8B"
  adaptive_icon_foreground: assets/images/icon/ic_launcher_foreground.png


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  fonts:
    - family: Whitney
      fonts:
        - asset: assets/fonts/Whitney-Book.ttf
        - asset: assets/fonts/Whitney-BookItalic.ttf
          style: italic

  uses-material-design: true

  assets:
     - assets/
     - assets/images/icon/ic_launcher.png
     - assets/images/ic_person.png
     - assets/images/ic_sync_white_24dp.png
     - assets/images/minotaur.png
     - assets/images/lock.png
     - CHANGELOG.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
