name: flutter_app
description: Another v2ex unoffical app in flutter.And 'V2lf' means 'way to love flutter'.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.6.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  flutter_markdown: ^0.2.0
  shared_preferences: ^0.5.1+2
  url_launcher: ^5.0.2
  cached_network_image: ^0.7.0 # https://pub.dartlang.org/packages/cached_network_image
  html: ^0.13.3+3 # https://pub.flutter-io.cn/packages/html
  xpath: ^0.1.0 # https://pub.flutter-io.cn/packages/xpath     还不支持 ETree.toString(Element) :(
  dio: ^1.0.13 # https://pub.dartlang.org/packages/dio
  rxdart: ^0.20.0 # https://pub.flutter-io.cn/packages/rxdart
  # flutter_html_view: ^0.5.10 # https://pub.flutter-io.cn/packages/flutter_html_view "Thus, flutter_html_view ^0.5.10 requires url_launcher ^3.0.0."
  flutter_html: ^0.9.6 # https://github.com/Sub6Resources/flutter_html
  fluttertoast: ^2.2.3 # https://pub.dartlang.org/packages/fluttertoast
  fluintl: ^0.1.2 # 多语言 国际化 https://pub.dartlang.org/packages/fluintl
  intl: ^0.15.7 # https://pub.dartlang.org/packages/intl
  # flutter_inappbrowser: ^0.5.51 #https://pub.dartlang.org/packages/flutter_inappbrowser
  # flame: ^0.10.2
  path_provider: ^0.5.0+1 # https://pub.dartlang.org/packages/path_provider#-installing-tab-
  modal_progress_hud: ^0.1.3 # https://github.com/mmcc007/modal_progress_hud
  ovprogresshud: ^0.2.1 # https://github.com/mjl0602/OVProgressHUD
  event_bus: ^1.0.3 # https://pub.dartlang.org/packages/event_bus
  flare_flutter: ^1.3.6 # https://pub.dartlang.org/packages/flare_flutter#-installing-tab-
  share: ^0.6.0+1 # https://pub.dartlang.org/packages/share#-installing-tab-
  launch_review: ^2.0.0 # https://pub.dartlang.org/packages/launch_review#-installing-tab-
  font_awesome_flutter: ^8.4.0 # https://pub.dartlang.org/packages/font_awesome_flutter#-installing-tab-
  webfeed: ^0.4.2 # https://github.com/witochandra/webfeed
  flutter_whatsnew: ^0.2.0+3 # https://pub.dartlang.org/packages/flutter_whatsnew#-installing-tab-

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
  intl_translation: ^0.17.2 # https://pub.dartlang.org/packages/intl_translation

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/images/icon/ic_launcher.png
  image_path_ios: assets/images/icon/ios.png
  adaptive_icon_background: "#607D8B"
  adaptive_icon_foreground: assets/images/icon/ic_launcher_foreground.png


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Whitney
      fonts:
        - asset: assets/fonts/Whitney-Book.ttf
        - asset: assets/fonts/Whitney-BookItalic.ttf
          style: italic

#    - family: Ubuntu
#      fonts:
#        - asset: assets/fonts/Ubuntu-Regular.ttf
#
#    - family: NotoSerifSC
#      fonts:
#        - asset: assets/fonts/NotoSerifSC-Regular.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/
     - assets/images/icon/ic_launcher.png
     - assets/images/ic_person.png
     - assets/images/logo_v2lf.png
     - assets/images/ic_sync_white_24dp.png
     - assets/images/minotaur.png
     - CHANGELOG.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
