name: flutter_app
description: Another v2ex unofficial app in flutter.And 'V2lf' means 'way to love flutter'.

version: 2020.9+44

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ^0.5.6+2
  url_launcher: ^5.5.0 # https://pub.flutter-io.cn/packages/url_launcher#-installing-tab-
  cached_network_image: ^2.2.0+1 # https://pub.dartlang.org/packages/cached_network_image
  html: ^0.14.0+3 # https://pub.flutter-io.cn/packages/html
  xpath: ^0.1.0 # https://pub.flutter-io.cn/packages/xpath     还不支持 ETree.toString(Element) :(
  dio: ^3.0.10 # https://pub.dartlang.org/packages/dio
  dio_cookie_manager: ^1.0.0 # https://pub.dev/packages/dio_cookie_manager#-installing-tab-
  dio_http_cache: ^0.2.6 # https://github.com/hurshi/dio-http-cache
  flutter_html: ^1.0.2 # https://pub.dev/packages/flutter_html#-installing-tab-
  fluttertoast: ^7.0.4 # https://pub.dartlang.org/packages/fluttertoast
  path_provider: ^1.6.8 # https://pub.dartlang.org/packages/path_provider#-installing-tab-
  sqflite: ^1.3.0+1 # https://pub.dev/packages/sqflite#-installing-tab-
  # ovprogresshud: ^0.2.5 # https://github.com/mjl0602/OVProgressHUD
  ovprogresshud:  # 官方有bug尚未修复，fork后自己修复的
    git:
      url: https://github.com/w4mxl/OVProgressHUD.git
  flare_flutter: ^2.0.3 # https://pub.dartlang.org/packages/flare_flutter#-installing-tab-
  # flare_flutter:
  #   git:
  #     url: https://github.com/2d-inc/Flare-Flutter.git
  #     path: flare_flutter
  #     ref: dev
  share: ^0.6.4+3 # https://pub.dartlang.org/packages/share#-installing-tab-
  launch_review: ^2.0.0 # https://pub.dartlang.org/packages/launch_review#-installing-tab-
  font_awesome_flutter: ^8.8.1 # https://pub.dartlang.org/packages/font_awesome_flutter#-installing-tab-
  webfeed: ^0.5.2 # https://github.com/witochandra/webfeed
  # flutter_whatsnew: ^1.0.3 # https://pub.dartlang.org/packages/flutter_whatsnew#-installing-tab-
  # flutter_whatsnew 目前存在问题，fork 后修改源码了
  flutter_whatsnew:
    git:
      url: https://github.com/w4mxl/flutter_whatsnew.git
  shimmer: ^1.0.1
  # https://github.com/memspace/zefyr/issues/210
  # https://github.com/memspace/zefyr/issues/214
  zefyr:
      git:
        url: https://github.com/memspace/zefyr.git
        path: packages/zefyr
  # zefyr: ^0.11.0 # https://pub.dartlang.org/packages/zefyr#-installing-tab-
  photo_view: ^0.9.2 # https://github.com/renancaraujo/photo_view/releases
  # webview_flutter: ^0.3.6 无法弹出键盘输入的问题还没解决
  flutter_webview_plugin: ^0.3.11
  flutter_local_notifications: ^1.1.6 # https://pub.dev/packages/flutter_local_notifications#-installing-tab-
  provider: ^4.0.4 # https://pub.dev/packages/provider
  device_info: ^0.4.1+5
  like_button: ^0.2.0
  responsive_builder: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  # pedantic: ^1.9.2

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/images/icon/ic_launcher.png
  image_path_ios: assets/images/icon/ios.png
  adaptive_icon_background: "#607D8B"
  adaptive_icon_foreground: assets/images/icon/ic_launcher_foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

flutter:
  fonts:
    - family: Whitney
      fonts:
        - asset: assets/fonts/Whitney-Book.ttf
        - asset: assets/fonts/Whitney-BookItalic.ttf
          style: italic

  uses-material-design: true

  assets:
    - assets/
    - assets/images/icon/ic_launcher.png
    - assets/images/ic_person.png
    - assets/images/ic_sync_white_24dp.png
    - assets/images/minotaur.png
    - assets/images/lock.png
    - CHANGELOG.md
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
